#!/bin/bash
# Auto-generated by install-native-host.mjs — do not edit manually.
exec "/opt/homebrew/bin/node" --enable-source-maps "/Users/bytedance/sourcecode/wxw/28_mcpsrv_in_extension/packages/server/dist/nativeHost.js" "$@"
