#!/bin/bash
# Auto-generated by install-native-host.mjs — do not edit manually.
exec "/Users/fred/.brew/bin/node" --enable-source-maps "/Users/fred/sourcecode/agentstuff/browser_extension/packages/server/dist/nativeHost.js" "$@"
